// <auto-generated />
namespace TasksApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class tx_Durationtext2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tx_Durationtext2));
        
        string IMigrationMetadata.Id
        {
            get { return "202209040022540_tx_Durationtext2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
